services:
  app:
    build: ./app
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./images:/app/images
      - ./logs:/app/logs
    networks:
      - db-network
      - front-network
    depends_on:
      - db

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      - ./images:/images
      - ./logs:/var/log/nginx
    networks:
      - front-network
    depends_on:
      - app

  db:
    image: postgres:17-alpine
    container_name: db
    env_file:
      - ./.env
    networks:
      - db-network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  front-network:
  db-network:

volumes:
  db_data: